replicaCount: 1
image:
  registry: code.nextform.vn
  repository: viectot/frontend
  pullPolicy: IfNotPresent
  tag: "latest"
imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: "viectot-frontend"
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  containerPort: 3000

enableCors: true
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: viectot.nextform.vn
      paths:
        - path: /api/auth
          pathType: Prefix
        - path: /
          pathType: Prefix
  tls: []

httproute:
  enabled: true
  annotations: {}
  host: viectot.nextform.vn
  gateway:
    name: nextform-gateway
    namespace: nextform
    sectionName: nextform-https-gw
  paths:
    - type: PathPrefix
      value: /api/auth
    - type: PathPrefix
      value: /

resources: {}
livenessProbe: {}
readinessProbe: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}

extraEnvs:
  - name: NEXTAUTH_SECRET
    value: "hySZDRRtv5nPwDreXeGVwHxGzPQXZa5d"
  - name: NEXT_PUBLIC_ZALO_APP_ID
    value: "2873380454691200822"
  - name: NEXT_PUBLIC_ZALO_SECRET_KEY
    value: "XVBQ1X23hWqLEVAMMII9"
  - name: NEXT_PUBLIC_CLIENT_ID
    value: "8VMDljyXs92lXM15kEaS7LuXKvzQIns1"
