{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "viectot-frontend.fullname" . }}
  labels:
    {{- include "viectot-frontend.labels" . | nindent 4 }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  hostnames:
    - {{ .Values.httproute.host | quote }}
  parentRefs:
    - name: {{ .Values.httproute.gateway.name | quote }}
      namespace: {{ .Values.httproute.gateway.namespace }}
      sectionName: {{ .Values.httproute.gateway.sectionName }}
  rules:
    - backendRefs:
        - name: {{ include "viectot-frontend.fullname" . }}
          port: {{ .Values.service.port }}
      matches:
        {{- range .Values.httproute.paths }}
        - path:
            type: {{ .type }}
            value: {{ .value }}
        {{- end }}
{{- end }}
